"""Embed the reference artwork in art/ into main.js as data URIs.

Plethora Bits ship as a single source file (packaged assets are disabled),
so the painted reference panels travel inline between the @@ART markers.
Run from anywhere: python3 tools/build_art.py
"""
import base64
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
art = root / "art"
main = root / "main.js"
mime = {".jpg": "image/jpeg", ".png": "image/png", ".webp": "image/webp"}
lines = []
for f in sorted(art.iterdir()):
    if f.suffix not in mime:
        continue
    data = base64.b64encode(f.read_bytes()).decode()
    lines.append('      %s: "data:%s;base64,%s",' % (f.stem, mime[f.suffix], data))
block = "    // @@ART_BEGIN (generated by tools/build_art.py from art/ — do not edit by hand)\n    const ART_SRC = {\n" + "\n".join(lines) + "\n    };\n    // @@ART_END"
src = main.read_text(encoding="utf-8")
start = src.index("    // @@ART_BEGIN")
end = src.index("// @@ART_END") + len("// @@ART_END")
main.write_text(src[:start] + block + src[end:], encoding="utf-8")
print("embedded", len(lines), "images;", main.stat().st_size, "bytes")
