// Generated by tools/build-bit.mjs from src/ - edit the modules, not this file.
(() => {
"use strict";

// ==== src/00-core.js ====
// ---- Core: seeded randomness, noise, math and colour helpers ----------------
// Everything procedural is seeded from world coordinates so neighbouring tiles
// repaint identical strokes and the world never shows repeated stamps.

function hash2(x, y, seed) {
  let h = Math.imul(x | 0, 0x27d4eb2d) ^ Math.imul(y | 0, 0x165667b1) ^ Math.imul(seed | 0, 0x9e3779b1);
  h = Math.imul(h ^ (h >>> 15), 0x85ebca6b);
  h = Math.imul(h ^ (h >>> 13), 0xc2b2ae35);
  return (h ^ (h >>> 16)) >>> 0;
}

function rngFrom(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function vnoise(x, y, seed) {
  const xi = Math.floor(x), yi = Math.floor(y);
  const xf = x - xi, yf = y - yi;
  const u = xf * xf * (3 - 2 * xf), v = yf * yf * (3 - 2 * yf);
  const a = hash2(xi, yi, seed) / 4294967296;
  const b = hash2(xi + 1, yi, seed) / 4294967296;
  const c = hash2(xi, yi + 1, seed) / 4294967296;
  const d = hash2(xi + 1, yi + 1, seed) / 4294967296;
  return a + (b - a) * u + (c - a) * v + (a - b - c + d) * u * v;
}

function fbm(x, y, seed, octaves) {
  let sum = 0, amp = 0.5, norm = 0;
  for (let i = 0; i < (octaves || 4); i++) {
    sum += vnoise(x, y, seed + i * 131) * amp;
    norm += amp;
    amp *= 0.5;
    x *= 2.03;
    y *= 2.03;
  }
  return sum / norm;
}

const clamp = (v, a, b) => (v < a ? a : v > b ? b : v);
const lerp = (a, b, t) => a + (b - a) * t;
function smoothstep(a, b, v) {
  const t = clamp((v - a) / (b - a), 0, 1);
  return t * t * (3 - 2 * t);
}
function smin(a, b, k) {
  const h = Math.max(k - Math.abs(a - b), 0) / k;
  return Math.min(a, b) - h * h * k * 0.25;
}
function smax(a, b, k) {
  return -smin(-a, -b, k);
}

function hex(h) {
  const n = parseInt(h.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}
function mixRGB(a, b, t) {
  return [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t];
}
function css(c, alpha) {
  return `rgba(${c[0] | 0},${c[1] | 0},${c[2] | 0},${alpha === undefined ? 1 : alpha})`;
}
// Brighten (dv > 0) toward warm cream or darken (dv < 0) toward cool violet,
// the way the reference shifts hue with value instead of adding black/white.
function shade(c, dv) {
  if (dv >= 0) return mixRGB(c, [255, 244, 228], clamp(dv, 0, 1));
  return mixRGB(c, [74, 62, 104], clamp(-dv, 0, 1));
}
function ramp(stops, t) {
  t = clamp(t, 0, 1) * (stops.length - 1);
  const i = Math.min(Math.floor(t), stops.length - 2);
  return mixRGB(stops[i], stops[i + 1], t - i);
}

// ==== src/10-palette.js ====
// ---- Palette: sampled by eye from the approved reference -----------------------
// Dusty lavender shadows, warm peach light, cream fur, sage moss, rose spires,
// and a rust-orange explorer that stays readable against all of it.

const PAL = {
  skyZenith: hex("#6d7cb2"),
  skyHigh: hex("#9ba2cb"),
  skyMid: hex("#cfb3c3"),
  skyLow: hex("#f1c6a2"),
  horizon: hex("#fbdcaa"),
  sunCore: hex("#fff3d2"),
  cloudLit: hex("#fde3c4"),
  cloudMid: hex("#e8c3bd"),
  cloudShade: hex("#a99cc4"),
  cloudDeep: hex("#8b86b6"),
  mistWarm: hex("#f4dfcc"),
  mistCool: hex("#c7bdd9"),

  fur: [hex("#6a6189"), hex("#9a8db2"), hex("#d3aea6"), hex("#efd2bb"), hex("#fcf0df")],
  furRim: hex("#ffcc98"),
  furBounce: hex("#b4b1d8"),

  spire: [hex("#8d7aa2"), hex("#c597a2"), hex("#e7b9ad"), hex("#f6dccd")],
  skin: [hex("#8a7598"), hex("#c49aa6"), hex("#e7c2b5"), hex("#f6e0d2")],
  earInner: hex("#cf7f8a"),
  lash: hex("#3d3048"),

  moss: [hex("#3f4a36"), hex("#5d6b45"), hex("#7f8c56"), hex("#a8ad6b"), hex("#d3c98d")],
  shroomCap: [hex("#8e5873"), hex("#c06a72"), hex("#dd8a7c"), hex("#f2b39a")],
  shroomGill: [hex("#9a87a6"), hex("#dcbcb0"), hex("#f2dccb")],
  shroomStem: [hex("#9b8aa8"), hex("#e2cdbf"), hex("#f7ebdc")],

  explorer: {
    tunic: hex("#c5623b"),
    tunicLit: hex("#ea8a55"),
    tunicShade: hex("#8a4440"),
    trousers: hex("#363047"),
    trousersLit: hex("#5a4f69"),
    boots: hex("#2a2331"),
    skin: hex("#b97a5c"),
    skinLit: hex("#dc9f78"),
    hair: hex("#231c29"),
    hairLit: hex("#4a3a4c")
  }
};

// ==== src/20-anatomy.js ====
// ---- Anatomy: the creature as one signed-distance + relief field ------------
// A body is a set of primitives (spine capsules, fur lobes, spires, ear,
// mushrooms). Two fields come out of the same primitives:
//   sd(x, y) - signed distance to the silhouette (inside < 0). Collision is
//              the sd = 0 isoline, so terrain and painting cannot disagree.
//   h(x, y)  - relief height facing the camera, used only for lighting.
// World units are metres, x right, y up.

const MAT_FUR = 0, MAT_SPIRE = 1, MAT_SKIN = 2, MAT_EAR = 3, MAT_SHROOM = 4;
const SEG = 0, ELL = 1;

function sdUnevenCapsule(px, py, ax, ay, ra, bx, by, rb) {
  px -= ax;
  py -= ay;
  const vx = bx - ax, vy = by - ay;
  const h = vx * vx + vy * vy;
  const qx = Math.abs((px * vy - py * vx) / h);
  const qy = (px * vx + py * vy) / h;
  const b = (ra - rb) / Math.sqrt(h);
  const cx = Math.sqrt(Math.max(1 - b * b, 1e-6)), cy = b;
  const k = cx * qy - cy * qx;
  const m = cx * qx + cy * qy;
  const n = qx * qx + qy * qy;
  const len = Math.sqrt(h);
  if (k < 0) return len * Math.sqrt(n) - ra;
  if (k > cx) return len * Math.sqrt(n + 1 - 2 * qy) - rb;
  return len * m - ra;
}

class Anatomy {
  constructor(name) {
    this.name = name;
    this.prims = [];
  }

  seg(ax, ay, ra, bx, by, rb, o) {
    return this.add({
      kind: SEG, ax, ay, ra, bx, by, rb,
      minX: Math.min(ax - ra, bx - rb), maxX: Math.max(ax + ra, bx + rb),
      minY: Math.min(ay - ra, by - rb), maxY: Math.max(ay + ra, by + rb)
    }, o);
  }

  ell(cx, cy, a, b, rot, o) {
    const r = Math.max(a, b);
    return this.add({
      kind: ELL, cx, cy, a, b, cos: Math.cos(rot), sin: Math.sin(rot),
      minX: cx - r, maxX: cx + r, minY: cy - r, maxY: cy + r
    }, o);
  }

  add(p, o) {
    p.mat = o.mat ?? MAT_FUR;
    p.k = o.k ?? 2; // silhouette blend radius
    p.hk = o.hk ?? p.k; // relief blend radius
    p.hs = o.hs ?? 0.55; // relief height scale
    p.hz = o.hz ?? 0; // ellipse dome height
    p.base = o.base ?? 0; // relief offset (stacks a form in front of another)
    p.tag = o.tag || null;
    // Outside its silhouette a form's relief drops away; forms stacked in front
    // (large base) drop instantly so they never shade their surroundings.
    p.fall = p.base > 3 ? 1e3 : 3;
    p.id = this.prims.length;
    this.prims.push(p);
    return p;
  }

  cull(x0, y0, x1, y1) {
    const out = [];
    for (const p of this.prims) {
      const m = p.k * 2;
      if (p.maxX + m >= x0 && p.minX - m <= x1 && p.maxY + m >= y0 && p.minY - m <= y1) out.push(p);
    }
    return out;
  }

  bounds() {
    let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
    for (const p of this.prims) {
      x0 = Math.min(x0, p.minX); x1 = Math.max(x1, p.maxX);
      y0 = Math.min(y0, p.minY); y1 = Math.max(y1, p.maxY);
    }
    return { x0, y0, x1, y1 };
  }

  // Evaluates both fields at (x, y). `out` receives sd, h, mat and prim (the
  // primitive whose surface is frontmost there).
  eval(x, y, prims, out) {
    let sd = 1e9, h = -1e9, bestH = -1e9, bestSd = 1e9, front = null, nearest = null;
    for (let i = 0; i < prims.length; i++) {
      const p = prims[i];
      let d, hv;
      if (p.kind === SEG) {
        d = sdUnevenCapsule(x, y, p.ax, p.ay, p.ra, p.bx, p.by, p.rb);
        const vx = p.bx - p.ax, vy = p.by - p.ay;
        const t = clamp(((x - p.ax) * vx + (y - p.ay) * vy) / (vx * vx + vy * vy), 0, 1);
        const dx = x - (p.ax + vx * t), dy = y - (p.ay + vy * t);
        const r = p.ra + (p.rb - p.ra) * t;
        const q = r * r - dx * dx - dy * dy;
        hv = q > 0 ? Math.sqrt(q) * p.hs + p.base : p.base - d * p.fall;
      } else {
        const lx = (x - p.cx) * p.cos + (y - p.cy) * p.sin;
        const ly = -(x - p.cx) * p.sin + (y - p.cy) * p.cos;
        const q = Math.sqrt((lx / p.a) * (lx / p.a) + (ly / p.b) * (ly / p.b));
        d = (q - 1) * Math.min(p.a, p.b);
        hv = q < 1 ? p.hz * Math.sqrt(1 - q * q) + p.base : p.base - d * p.fall;
      }
      sd = p.k > 0.01 ? smin(sd, d, p.k) : Math.min(sd, d);
      h = smax(h, hv, p.hk);
      if (d < 0.05 && hv > bestH) { bestH = hv; front = p; }
      if (d < bestSd) { bestSd = d; nearest = p; }
    }
    out.sd = sd;
    out.h = h;
    out.prim = front || nearest;
    out.mat = out.prim ? out.prim.mat : MAT_FUR;
    return out;
  }

  sdAt(x, y) {
    const o = {};
    return this.eval(x, y, this.cull(x - 1, y - 1, x + 1, y + 1), o).sd;
  }

  // Walks down from (x, yFrom) and returns the first surface height, or null.
  surfaceBelow(x, yFrom, yTo) {
    const prims = this.cull(x - 1, yTo - 1, x + 1, yFrom + 1);
    const o = {};
    let prev = yFrom;
    if (this.eval(x, yFrom, prims, o).sd < 0) return null;
    for (let y = yFrom - 0.2; y >= yTo; y -= 0.2) {
      if (this.eval(x, y, prims, o).sd < 0) {
        let lo = y, hi = prev;
        for (let i = 0; i < 14; i++) {
          const mid = (lo + hi) / 2;
          if (this.eval(x, mid, prims, o).sd < 0) lo = mid; else hi = mid;
        }
        return hi;
      }
      prev = y;
    }
    return null;
  }
}

// A primitive's own relief (no blending, no base): used to light forms
// stacked in front of the body from their own shape.
function primRelief(p, x, y) {
  if (p.kind === SEG) {
    const vx = p.bx - p.ax, vy = p.by - p.ay;
    const t = clamp(((x - p.ax) * vx + (y - p.ay) * vy) / (vx * vx + vy * vy), 0, 1);
    const dx = x - (p.ax + vx * t), dy = y - (p.ay + vy * t);
    const r = p.ra + (p.rb - p.ra) * t;
    return Math.sqrt(Math.max(r * r - dx * dx - dy * dy, 0)) * p.hs;
  }
  const lx = (x - p.cx) * p.cos + (y - p.cy) * p.sin;
  const ly = -(x - p.cx) * p.sin + (y - p.cy) * p.cos;
  const q = (lx / p.a) * (lx / p.a) + (ly / p.b) * (ly / p.b);
  return p.hz * Math.sqrt(Math.max(1 - q, 0));
}

function catmullRom(p0, p1, p2, p3, t) {
  const t2 = t * t, t3 = t2 * t;
  return 0.5 * (2 * p1 + (-p0 + p2) * t + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t2 + (-p0 + 3 * p1 - 3 * p2 + p3) * t3);
}

// Smooth spine through control points [x, y, radius].
function sampleSpine(ctrl, perSpan) {
  const out = [];
  const P = (i) => ctrl[clamp(i, 0, ctrl.length - 1)];
  for (let i = 0; i < ctrl.length - 1; i++) {
    for (let s = 0; s < perSpan; s++) {
      const t = s / perSpan;
      const v = [0, 1, 2].map((k) => catmullRom(P(i - 1)[k], P(i)[k], P(i + 1)[k], P(i + 2)[k], t));
      out.push(v);
    }
  }
  out.push(ctrl[ctrl.length - 1].slice());
  return out;
}

// Interpolated spine sample at height y (spine must rise monotonically there).
function spineAtY(samples, y) {
  for (let i = 0; i < samples.length - 1; i++) {
    const a = samples[i], b = samples[i + 1];
    if ((y >= a[1] && y <= b[1]) || (y <= a[1] && y >= b[1])) {
      const t = (y - a[1]) / (b[1] - a[1] || 1);
      return [lerp(a[0], b[0], t), y, lerp(a[2], b[2], t)];
    }
  }
  return y < samples[0][1] ? samples[0] : samples[samples.length - 1];
}

function addSpine(anat, samples, o) {
  for (let i = 0; i < samples.length - 1; i++) {
    const a = samples[i], b = samples[i + 1];
    anat.seg(a[0], a[1], a[2], b[0], b[1], b[2], o);
  }
}

// Relief height of what is already in `anat` at (x, y); used to stack new
// forms on top of the body so they read as growing out of it.
function reliefAt(anat, x, y) {
  return anat.eval(x, y, anat.cull(x - 1, y - 1, x + 1, y + 1), {}).h;
}

// ==== src/25-world.js ====
// ---- World: one sleeping creature laid across depth layers ------------------
// The creature lies diagonally up a slope, facing left, as in the reference
// title panel: tail low on the right, back rising up-left, shoulder, neck,
// and the head at the top with its muzzle to the left. The low sun sits on
// the right, so the climbing surface (the back) faces the light.
//
// play  (depth 1.0)  - the body the explorer climbs. Its upper-right face is
//                      the route: fur shelves on the back make the treads.
// flank (depth 0.55) - the creature's far flank and dorsal spires, behind.
// tail  (depth 0.2)  - the tail curling up out of the cloud sea.
// fore  (depth 1.5)  - near fur clumps that frame the bottom of the screen.
// Props (mushrooms, trees, the closed eye) are rooted on anatomy surfaces.

const EXPLORER_HEIGHT = 1.5;
const SUN_SIDE = 1; // +1: sun on the right

// Point on the dorsal (sun-facing, upper-right) surface of a spine sample.
function dorsalAt(samples, i) {
  const a = samples[Math.max(0, i - 1)], b = samples[Math.min(samples.length - 1, i + 1)];
  let tx = b[0] - a[0], ty = b[1] - a[1];
  const l = Math.hypot(tx, ty) || 1;
  tx /= l; ty /= l;
  const nx = ty, ny = -tx; // right-hand normal: up-right for a spine rising up-left
  const s = samples[i];
  return { x: s[0] + nx * s[2], y: s[1] + ny * s[2], nx, ny, tx, ty, r: s[2], cx: s[0], cy: s[1] };
}

function buildWorld(seed) {
  const rnd = rngFrom(seed);
  const R = (a, b) => a + (b - a) * rnd();

  // -- Play layer: the climbable body ---------------------------------------
  const play = new Anatomy("play");
  const spine = sampleSpine([
    [70, -80, 46], [46, -14, 40], [22, 34, 36], [-2, 78, 33], [-26, 116, 31],
    [-48, 154, 29], [-62, 192, 25], [-65, 224, 19], [-60, 250, 14], [-57, 270, 12.5]
  ], 8);
  addSpine(play, spine, { k: 8, hk: 6, hs: 0.5 });

  // Head, facing left: furred cranium, muzzle, cheek ruff, two ears.
  const HX = -58; // head sits over the neck, muzzle forward (left)
  // Forelimb stretched up-slope with the chin resting on it: upper arm along
  // the neck, forearm under the jaw, a broad paw with toe lobes.
  play.seg(-46, 206, 11, -42, 240, 8.5, { k: 5, hk: 4, hs: 0.5, base: 1 });
  play.seg(-42, 240, 8.5, -58, 260, 6.8, { k: 4, hk: 3, hs: 0.5, base: 2 });
  play.seg(-58, 260, 6.8, -72, 261, 6, { k: 3, hk: 3, hs: 0.5, base: 2.5 });
  play.ell(-79, 259.5, 6.5, 4.6, 0.05, { k: 2.5, hk: 2, hz: 3, base: 3 });
  for (const [tx, ty, ta] of [[-84.5, 257.5, 2.2], [-83, 262, 2.1], [-79.5, 264.2, 2]]) {
    play.ell(tx, ty, ta, ta * 0.72, 0.3, { k: 1, hk: 1, hz: 1.4, base: 5, tag: "lobe" });
  }
  play.ell(HX, 284, 14, 10.5, 0.12, { k: 6, hk: 4, hz: 9, base: 2, tag: "cranium" });
  play.ell(HX - 13.5, 279, 7.5, 5.5, 0.25, { k: 3.5, hk: 3, hz: 4, base: 6, tag: "muzzle" });
  play.ell(HX + 12, 274, 7, 8.5, -0.3, { k: 4, hk: 3, hz: 5, base: 4 });
  play.seg(HX - 3, 292, 3.4, HX - 5, 302, 2.0, { mat: MAT_EAR, k: 2, hk: 1.5, hs: 0.4, base: 1, tag: "ear-far" });
  play.seg(HX + 7, 290, 6.6, HX + 12.5, 309, 3.4, { mat: MAT_EAR, k: 2.4, hk: 1.5, hs: 0.6, base: 9, tag: "ear" });

  // Fur shelves on the back: drooping lobes whose flat-ish tops are the
  // treads of the climb, spaced by distance along the back so the route is a
  // staircase of rounded fur ledges. They belong to the body field, so every
  // shelf is painted fur and walkable ground at once.
  const dorsal = [];
  for (let i = 1; i < spine.length - 1; i++) dorsal.push(dorsalAt(spine, i));
  const shelves = [];
  let dist = 0, next = 2;
  for (let i = 1; i < dorsal.length; i++) {
    const p0 = dorsal[i - 1], p1 = dorsal[i];
    const segLen = Math.hypot(p1.x - p0.x, p1.y - p0.y);
    while (next <= dist + segLen) {
      const t = (next - dist) / segLen;
      const x = lerp(p0.x, p1.x, t), y = lerp(p0.y, p1.y, t);
      if (y > 262) break;
      const roll = rnd();
      const big = roll < 0.2, tiny = roll > 0.82;
      const a = big ? R(4.6, 6.6) : tiny ? R(1.6, 2.3) : R(2.3, 3.9);
      const b = a * R(0.32, 0.5);
      const cx = x + a * R(0.5, 0.8), cy = y - b * R(0.2, 0.6);
      play.ell(cx, cy, a, b, -R(0.0, 0.2), { k: R(0.5, 0.9), hk: 1.2, hz: b * 1.3, base: 0.8, tag: "shelf" });
      shelves.push({ x: cx, y: cy, a, b });
      if (big && rnd() < 0.6) {
        // A smaller lobe tucked beside a big one: ledges grow in clusters.
        const a2 = a * R(0.4, 0.6);
        play.ell(cx + a * R(0.5, 0.8), cy - b * R(0.5, 1.0), a2, a2 * R(0.35, 0.5), -R(0.05, 0.3), { k: 0.8, hk: 1.2, hz: a2 * 0.5, base: 0.8, tag: "shelf" });
      }
      next += (tiny ? R(2.2, 3) : R(3, 5.2)) + (big ? R(0.8, 2.2) : 0);
    }
    dist += segLen;
  }
  // Soft lobes along the belly side so the lower silhouette is never a tube.
  for (let i = 1; i < spine.length - 2; i += 1 + Math.floor(rnd() * 2)) {
    const s = spine[i];
    const d = dorsalAt(spine, i);
    const a = R(4, 8);
    play.ell(s[0] - d.nx * s[2], s[1] - d.ny * s[2], a, a * R(0.45, 0.6), R(0.05, 0.3), { k: 3, hk: 2, hz: a * 0.5, base: 0.4, tag: "lobe" });
  }

  // Interior fur masses on the flank facing the camera: big soft forms so the
  // body reads as rounded anatomy rather than a flat fill.
  for (let i = 0; i < spine.length; i++) {
    const d = dorsalAt(spine, i);
    if (d.cy > 205) break;
    const n = rnd() < 0.5 ? 1 : 0;
    for (let j = 0; j < n; j++) {
      const depth = R(4, d.r * 1.6);
      const x = d.x - d.nx * depth + d.tx * R(-3, 3), y = d.y - d.ny * depth + d.ty * R(-3, 3);
      const a = R(7, 13), b = a * R(0.5, 0.7), hz = R(1.6, 3);
      const base = reliefAt(play, x, y) - hz * 0.6;
      play.ell(x, y, a, b, Math.atan2(d.ty, d.tx) + R(-0.3, 0.3), { k: 0.5, hk: 5, hz, base });
    }
  }

  // Dorsal spires rising from the back (rose-cream monoliths) - landmarks on
  // the route, like the reference BACK panel. Placed by height on the back.
  const backAt = (y) => {
    let best = dorsal[0];
    for (const d of dorsal) if (Math.abs(d.y - y) < Math.abs(best.y - y)) best = d;
    return best;
  };
  for (const [y, len, lean, ra] of [[140, 15, -0.12, 2.6], [176, 21, 0.06, 3.4], [206, 13, -0.2, 2.2], [92, 12, 0.1, 2.2]]) {
    const d = backAt(y);
    const ax = d.x - d.nx * 2.2, ay = d.y - d.ny * 2.2;
    const bx = ax + Math.sin(lean) * len, by = ay + Math.cos(lean) * len;
    const base = reliefAt(play, ax, ay) + 1.5;
    play.seg(ax, ay, ra, bx, by, ra * 0.5, { mat: MAT_SPIRE, k: 1.0, hk: 1.2, hs: 0.7, base });
  }

  // -- Props rooted on the body ---------------------------------------------
  const props = { mushrooms: [], trees: [], eyes: [] };
  props.eyes.push({ x: HX - 5.5, y: 284.5, w: 5.8, tilt: 0.1, outer: 1 });

  function addMushroom(x, yHint, capR, stemH, lean) {
    const y = play.surfaceBelow(x, yHint + 10, yHint - 14);
    if (y === null) return false;
    const root = { x, y: y - 0.3 };
    const top = { x: x + lean, y: y + stemH };
    play.seg(root.x, root.y, 0.32 + capR * 0.05, top.x, top.y, 0.24 + capR * 0.04, { mat: MAT_SHROOM, k: 0, hk: 0.01, base: 30 });
    play.ell(top.x, top.y + capR * 0.12, capR, capR * 0.32, 0, { mat: MAT_SHROOM, k: 0, hk: 0.01, hz: 1, base: 31 });
    props.mushrooms.push({ root, top, capR });
    return true;
  }
  function addTree(x, yHint, h, kind) {
    const y = play.surfaceBelow(x, yHint + 10, yHint - 14);
    if (y !== null) props.trees.push({ x, y, h, kind, seed: hash2(x * 10, y * 10, seed) });
  }

  // A standing spot on top of a shelf (searches across the tread).
  function standOn(s) {
    for (const f of [0.2, 0.35, 0.05, 0.5, 0.65, 0.8]) {
      const x = s.x + s.a * f;
      const y = play.surfaceBelow(x, s.y + s.b + 7, s.y - s.b - 3);
      if (y !== null && y > s.y - s.b * 0.5) return { x, y };
    }
    return null;
  }
  const nearestShelf = (y, ok) => {
    let best = null;
    for (const s of shelves) if ((!best || Math.abs(s.y - y) < Math.abs(best.y - y)) && (!ok || ok(s))) best = s;
    return best;
  };

  // The gameplay showcase: the shelf on the back nearest 124 m.
  const show = nearestShelf(124, (s) => standOn(s));
  const { x: gx, y: gy } = standOn(show);
  addTree(gx + 2.2, gy + 1, 2.6, "cypress");
  addTree(gx - 2.8, gy + 7, 3.4, "cypress");
  addTree(gx + 4, gy - 4, 1.6, "shrub");
  // Sparse vegetation along the rest of the back.
  for (const s of shelves) {
    if (Math.abs(s.y - gy) > 14 && rnd() < 0.35) addTree(s.x + R(-s.a * 0.2, s.a * 0.5), s.y + s.b + 4, R(1.2, 3.2), rnd() < 0.5 ? "shrub" : "cypress");
  }
  addMushroom(gx - 4.2, gy + 6, 1.9, 2.4, -0.4);
  addMushroom(gx + 5.5, gy - 7, 1.4, 1.6, 0.3);
  addMushroom(gx - 7.8, gy + 9, 1.1, 1.3, -0.2);

  // Establishing: on a shelf of the neck, below and behind the head.
  // Establishing: standing on the brow, right above the closed eye (the
  // reference's summit panel) - a spot the climb really reaches.
  const ex = HX - 11;
  const ey = play.surfaceBelow(ex, 310, 270);
  if (ey === null) throw new Error("brow has no standing surface");
  const explorerSpots = {
    gameplay: { x: gx, y: gy, facing: -1 },
    establishing: { x: ex, y: ey, facing: -1 }
  };
  const focus = { head: { x: HX - 4, y: 285 } };

  // -- Flank layer: far side of the back curving away, behind mist ----------
  // A low, broad rolling form (not a second pillar) carrying a few spires.
  const flank = new Anatomy("flank");
  const flankSpine = sampleSpine([
    [130, -100, 46], [100, -20, 40], [70, 48, 34], [48, 88, 26], [38, 108, 16]
  ], 5);
  addSpine(flank, flankSpine, { k: 9, hk: 6, hs: 0.45 });
  for (let i = 1; i < flankSpine.length - 1; i++) {
    const d = dorsalAt(flankSpine, i);
    const a = R(5, 10);
    flank.ell(d.x + a * 0.15, d.y - a * 0.1, a, a * R(0.4, 0.5), -R(0.05, 0.2), { k: 2.5, hk: 2, hz: a * 0.5, base: 0.6 });
  }
  for (const [i, len, lean] of [[8, 26, 0.12], [12, 20, -0.05], [15, 15, 0.2]]) {
    const d = dorsalAt(flankSpine, Math.min(i, flankSpine.length - 2));
    const ax = d.x - d.nx * 3, ay = d.y - d.ny * 3;
    flank.seg(ax, ay, R(3.6, 4.8), ax + Math.sin(lean) * len, ay + Math.cos(lean) * len, R(1.6, 2.4),
      { mat: MAT_SPIRE, k: 1.5, hk: 1.5, hs: 0.7, base: reliefAt(flank, ax, ay) + 2 });
  }

  // -- Tail layer: the tail curling up out of the clouds ---------------------
  const tail = new Anatomy("tail");
  const tailSpine = sampleSpine([
    [70, -60, 15], [74, 30, 13], [68, 100, 11], [52, 142, 9], [30, 154, 7],
    [18, 144, 5.5], [21, 128, 4], [31, 126, 3]
  ], 6);
  addSpine(tail, tailSpine, { k: 4, hk: 3, hs: 0.5 });

  // -- Foreground: near fur clumps framing the bottom of the frame -----------
  const fore = new Anatomy("fore");
  const gs = explorerSpots.gameplay;
  fore.ell(gs.x - 3.6, gs.y - 5.4, 2.2, 1.5, 0.3, { k: 1, hk: 1, hz: 1.5, tag: "lobe" });
  fore.ell(gs.x - 1.4, gs.y - 5.9, 2.0, 1.4, -0.15, { k: 1, hk: 1, hz: 1.4, tag: "lobe" });
  fore.ell(gs.x + 4.4, gs.y - 5.6, 2.2, 1.3, -0.3, { k: 1, hk: 1, hz: 1.3, tag: "lobe" });

  return {
    seed,
    spine,
    layers: { play, flank, tail, fore },
    props,
    explorerSpots,
    focus
  };
}

// ==== src/30-brush.js ====
// ---- Brush primitives -------------------------------------------------------
// All marks are filled shapes with soft value shifts, not outlines: tapered
// fur locks, round dabs for moss and leaves, and long thin streaks.

function makeCanvas(w, h) {
  if (typeof OffscreenCanvas !== "undefined") return new OffscreenCanvas(w, h);
  const c = document.createElement("canvas");
  c.width = w;
  c.height = h;
  return c;
}

// A tapered lock of fur: rounded root, swelling body, pointed tip.
// (x, y) root in px, (dx, dy) unit direction in px space, bend in [-0.5, 0.5].
function lockPath(g, x, y, dx, dy, len, w, bend) {
  const px = -dy, py = dx;
  const bx = px * bend * len, by = py * bend * len;
  const tx = x + dx * len + bx, ty = y + dy * len + by;
  const mx = x + dx * len * 0.42 + bx * 0.5, my = y + dy * len * 0.42 + by * 0.5;
  g.beginPath();
  g.moveTo(x - px * w * 0.45, y - py * w * 0.45);
  g.quadraticCurveTo(mx - px * w * 0.7, my - py * w * 0.7, tx, ty);
  g.quadraticCurveTo(mx + px * w * 0.7, my + py * w * 0.7, x + px * w * 0.45, y + py * w * 0.45);
  g.quadraticCurveTo(x - dx * w * 0.55, y - dy * w * 0.55, x - px * w * 0.45, y - py * w * 0.45);
  g.closePath();
}

function drawLock(g, x, y, dx, dy, len, w, bend, col, alpha) {
  lockPath(g, x, y, dx, dy, len, w, bend);
  g.fillStyle = css(col, alpha);
  g.fill();
}

function dab(g, x, y, rx, ry, rot, col, alpha) {
  g.beginPath();
  g.ellipse(x, y, Math.max(rx, 0.3), Math.max(ry, 0.3), rot, 0, Math.PI * 2);
  g.fillStyle = css(col, alpha);
  g.fill();
}

function streak(g, x, y, dx, dy, len, width, col, alpha) {
  g.beginPath();
  g.moveTo(x, y);
  g.lineTo(x + dx * len, y + dy * len);
  g.lineCap = "round";
  g.lineWidth = Math.max(width, 0.5);
  g.strokeStyle = css(col, alpha);
  g.stroke();
}

// ==== src/35-fur.js ====
// ---- Fur: soft clumps, dripping tips, and a broken silhouette fringe ---------
// The reference fur is not hair noise: it is large, soft, rounded clumps lit
// on top and lavender underneath, ending in pointed tips that hang over the
// clump below. Fine detail lives at clump tips and at the silhouette only.

function clumpCell(L, k) { return Math.max(L.clumpCell, L.minClumpPx / k); }
function fringeCell(L, k) { return Math.max(L.fringeCell, L.minLockPx / k); }
function furReach(L, k) { return Math.max(clumpCell(L, k) * 3.2, fringeCell(L, k) * 4); }

// Flow: toward the tail, falling with gravity, combed outward at the
// silhouette and around relief forms.
function furDir(F, idx, nrm, L, X, Y, seed, edge, jitter) {
  F.normals(idx, nrm);
  const fl = L.flow || [0, -1];
  let dx = fl[0] * 0.75 + nrm.ox * edge * 0.95 - nrm.nx * 0.2;
  let dy = fl[1] * 0.75 - 0.45 + nrm.oy * edge * 0.95 - nrm.ny * 0.2;
  const ang = (vnoise(X * 0.28, Y * 0.28, seed + 3) - 0.5) * 0.8 + jitter;
  const ca = Math.cos(ang), sa = Math.sin(ang);
  const rx = dx * ca - dy * sa, ry = dx * sa + dy * ca;
  const l = Math.hypot(rx, ry) || 1;
  return [rx / l, ry / l];
}

// Lit colour at a world point, falling back toward the body interior when the
// point is off the fur (so fringe locks never sample empty sky).
function furColorAt(F, X, Y, seed, nrm, fallbackIdx) {
  let idx = F.index(X, Y);
  if (idx < 0 || F.sd[idx] > -0.05 || F.mat[idx] !== MAT_FUR) idx = fallbackIdx;
  const c = surfaceColor(F, idx, X, Y, seed, nrm);
  return { c, t: nrm.t };
}

// A tapered curved brush stroke (wide at the root, thin at the tip).
function g2Stroke(g, x, y, dx, dy, len, w, bend, col, alpha) {
  const px = -dy, py = dx;
  const tx = x + dx * len + px * bend * len, ty = y + dy * len + py * bend * len;
  const mx = x + dx * len * 0.5 + px * bend * len * 0.6, my = y + dy * len * 0.5 + py * bend * len * 0.6;
  g.beginPath();
  g.moveTo(x - px * w * 0.5, y - py * w * 0.5);
  g.quadraticCurveTo(mx - px * w * 0.35, my - py * w * 0.35, tx, ty);
  g.quadraticCurveTo(mx + px * w * 0.35, my + py * w * 0.35, x + px * w * 0.5, y + py * w * 0.5);
  g.arc(x, y, w * 0.5, Math.atan2(py, px), Math.atan2(py, px) + Math.PI);
  g.fillStyle = css(col, alpha);
  g.fill();
}

function paintFur(tg, F, L, x0, yTop, k, span, seed) {
  const nrm = {};
  const toPx = (X, Y) => [(X - x0) * k, (yTop - Y) * k];
  const reach = furReach(L, k);

  // Pass A: brush strokes. Short opaque streaks along the fur flow, a
  // little lighter on lit forms and a little darker in shade, so the fur
  // reads as gouache texture over the big lit forms beneath.
  const C = clumpCell(L, k);
  for (let cy = Math.floor((yTop - span - reach) / C); cy <= Math.ceil((yTop + reach) / C); cy++) {
    for (let cx = Math.floor((x0 - reach) / C); cx <= Math.ceil((x0 + span + reach) / C); cx++) {
      const r = rngFrom(hash2(cx, cy, seed));
      const X = (cx + r()) * C, Y = (cy + r()) * C;
      const idx = F.index(X, Y);
      if (idx < 0 || F.mat[idx] !== MAT_FUR || F.sd[idx] > -0.05) continue;
      const edge = 1 - smoothstep(0, 2.2, -F.sd[idx]);
      const [dx, dy] = furDir(F, idx, nrm, L, X, Y, seed, edge, (r() - 0.5) * 0.35);
      const base = surfaceColor(F, idx, X, Y, seed, nrm);
      const lit = nrm.t;
      const dv = (lit > 0.55 ? 0.1 : -0.08) + (r() - 0.5) * 0.16;
      const col = finishColor(shade(lit > 0.6 && r() < 0.3 ? mixRGB(base, PAL.furRim, 0.35) : base, dv), Y, L);
      const len = C * (2.2 + r() * 2.2) * k;
      const w = Math.max(1, C * (0.32 + r() * 0.3) * k);
      const [px, py] = toPx(X, Y);
      const bend = (r() - 0.5) * 0.25;
      g2Stroke(tg, px, py, dx, -dy, len, w, bend, col, 0.62 + r() * 0.3);
    }
  }

  // Pass B: silhouette fringe - small locks combed outward so the edge of the
  // body breaks up into fur instead of a hard outline.
  const f = fringeCell(L, k);
  for (let cy = Math.floor((yTop - span - reach) / f); cy <= Math.ceil((yTop + reach) / f); cy++) {
    for (let cx = Math.floor((x0 - reach) / f); cx <= Math.ceil((x0 + span + reach) / f); cx++) {
      const r = rngFrom(hash2(cx, cy, seed + 5));
      const X = (cx + r()) * f, Y = (cy + r()) * f;
      const idx = F.index(X, Y);
      if (idx < 0 || F.mat[idx] !== MAT_FUR) continue;
      const sd = F.sd[idx];
      if (sd > 0.05 || sd < -0.9) continue;
      const [dx, dy] = furDir(F, idx, nrm, L, X, Y, seed, 1, (r() - 0.5) * 0.5);
      const inner = F.index(X - nrm.ox * 0.6, Y - nrm.oy * 0.6);
      const col = furColorAt(F, X - nrm.ox * 0.6, Y - nrm.oy * 0.6, seed, nrm, inner < 0 ? idx : inner);
      const c = finishColor(shade(col.c, (r() - 0.5) * 0.12), Y, L);
      const [px, py] = toPx(X, Y);
      drawLock(tg, px, py, dx, -dy, f * (2.2 + r() * 1.6) * k, f * (0.2 + r() * 0.16) * k, (r() - 0.5) * 0.5, c, 0.92);
    }
  }
}

// Scalloped drips under every fur form (shelves, belly lobes, interior
// masses): pointed locks hang from each form's lower edge over the shadow
// beneath it - the signature edge of the reference fur.
function paintDrips(tg, F, L, prims, x0, yTop, k, span, seed) {
  const nrm = {};
  const spacing = Math.max(L.fringeCell * 0.75, 6 / k);
  const flow = L.flow || [0, -1];
  for (const p of prims) {
    if (p.kind !== ELL || p.mat !== MAT_FUR || (p.tag !== "shelf" && p.tag !== "lobe")) continue;
    if (p.maxX < x0 - 2 || p.minX > x0 + span + 2 || p.maxY < yTop - span - 3 || p.minY > yTop + 3) continue;
    const arc = Math.PI * (p.a + p.b) * 0.42;
    const n = Math.max(3, Math.round(arc / spacing));
    for (let i = 0; i <= n; i++) {
      const r = rngFrom(hash2(p.id * 977 + i, p.id, seed + 9));
      const th = Math.PI * (1.08 + 0.84 * (i + (r() - 0.5) * 0.6) / n);
      const lx = Math.cos(th) * p.a * 0.97, ly = Math.sin(th) * p.b * 0.97;
      const X = p.cx + lx * p.cos - ly * p.sin, Y = p.cy + lx * p.sin + ly * p.cos;
      const idx = F.index(X, Y);
      if (idx < 0) continue;
      // Only where this form is the visible surface (not buried in the body).
      const own = p.hz * 0.24 + p.base;
      if (F.h[idx] > own + 0.35 || F.sd[idx] < -1.4) continue;
      const inner = F.index(X - (lx * p.cos - ly * p.sin) * 0.25, Y - (lx * p.sin + ly * p.cos) * 0.25);
      const col = furColorAt(F, X, Y + p.b * 0.25, seed, nrm, inner < 0 ? idx : inner);
      let dx = flow[0] * 0.35 + Math.cos(th) * 0.2 + (r() - 0.5) * 0.3, dy = -1;
      const dl = Math.hypot(dx, dy);
      dx /= dl; dy /= dl;
      const len = Math.max(p.b * (0.45 + r() * 0.55), 12 / k);
      const w = spacing * (0.4 + r() * 0.25);
      const c0 = finishColor(shade(col.c, (r() - 0.5) * 0.08), Y, L);
      const c1 = finishColor(shade(mixRGB(col.c, PAL.fur[1], 0.15), -0.06), Y - len, L);
      const px = (X - x0) * k, py = (yTop - Y) * k;
      const sx = px - dx * len * k * 0.35, sy = py + dy * len * k * 0.35;
      const grad = tg.createLinearGradient(sx, sy, px + dx * len * k, py - dy * len * k);
      grad.addColorStop(0, css(c0, 0.95));
      grad.addColorStop(1, css(c1, 0.95));
      lockPath(tg, sx, sy, dx, -dy, len * k * 1.35, w * k, (r() - 0.5) * 0.35);
      tg.fillStyle = grad;
      tg.fill();
    }
  }
}

// ==== src/40-painter.js ====
// ---- Painter: turns an anatomy layer into painted, cached tiles -------------
// Per tile:
//   1. Sample sd / relief / material on a grid (with margin for brush reach).
//   2. Light the relief (low sun from the upper left), darken creases,
//      warm the rims and push fog in by depth: a soft painted under-layer.
//   3. Lay fur locks along the anatomy's flow (down the body, outward at the
//      silhouette so edges break up into fur), then moss, spire streaks and
//      rooted props.
// Marks are seeded by world cell, so tile borders are invisible.

const LIGHT = (() => {
  const v = [0.52 * SUN_SIDE, 0.52, 0.68];
  const l = Math.hypot(v[0], v[1], v[2]);
  return [v[0] / l, v[1] / l, v[2] / l];
})();
const LIGHT2 = (() => {
  const l = Math.hypot(LIGHT[0], LIGHT[1]);
  return [LIGHT[0] / l, LIGHT[1] / l];
})();

function fogColor(y) {
  return mixRGB(PAL.mistWarm, PAL.mistCool, smoothstep(40, 420, y));
}

const TILE = 512;

class FieldGrid {
  constructor(anat, prims, x0, yTop, step, n, mg) {
    const N = n + 2 * mg;
    this.N = N; this.n = n; this.mg = mg; this.step = step; this.x0 = x0; this.yTop = yTop;
    this.sd = new Float32Array(N * N);
    this.h = new Float32Array(N * N);
    this.mat = new Uint8Array(N * N);
    this.prim = new Array(N * N);
    const o = {};
    let any = false;
    for (let j = 0; j < N; j++) {
      const Y = yTop - (j - mg + 0.5) * step;
      for (let i = 0; i < N; i++) {
        const X = x0 + (i - mg + 0.5) * step;
        anat.eval(X, Y, prims, o);
        const idx = j * N + i;
        this.sd[idx] = o.sd;
        this.h[idx] = o.h;
        this.mat[idx] = o.mat;
        this.prim[idx] = o.prim;
        if (o.sd < 2) any = true;
      }
    }
    this.any = any;
    this.cav = this.cavity(Math.max(1, Math.round(1.3 / step)));
  }

  // Box-blurred relief minus relief: positive in creases and folds.
  cavity(r) {
    const N = this.N, src = this.h, tmp = new Float32Array(N * N), out = new Float32Array(N * N);
    const pass = (from, to, horizontal) => {
      for (let a = 0; a < N; a++) {
        let sum = 0, cnt = 0;
        const at = (b) => (horizontal ? a * N + b : b * N + a);
        for (let b = 0; b < Math.min(r, N); b++) { sum += Math.max(from[at(b)], 0); cnt++; }
        for (let b = 0; b < N; b++) {
          if (b + r < N) { sum += Math.max(from[at(b + r)], 0); cnt++; }
          if (b - r - 1 >= 0) { sum -= Math.max(from[at(b - r - 1)], 0); cnt--; }
          to[at(b)] = sum / cnt;
        }
      }
    };
    pass(src, tmp, true);
    pass(tmp, out, false);
    for (let i = 0; i < N * N; i++) out[i] = out[i] - Math.max(src[i], 0);
    return out;
  }

  index(X, Y) {
    const i = Math.floor((X - this.x0) / this.step + this.mg);
    const j = Math.floor((this.yTop - Y) / this.step + this.mg);
    if (i < 1 || j < 1 || i >= this.N - 1 || j >= this.N - 1) return -1;
    return j * this.N + i;
  }

  // Relief normal (camera-facing 3D) and silhouette normal (in-plane, outward).
  normals(idx, out) {
    const N = this.N, s2 = this.step * 2, h = this.h, hc = h[idx];
    const p = this.prim[idx];
    if (p && p.fall > 3) {
      // Stacked forms are lit from their own shape so their edges never alias.
      const X = this.x0 + ((idx % N) - this.mg + 0.5) * this.step;
      const Y = this.yTop - (Math.floor(idx / N) - this.mg + 0.5) * this.step;
      const e = this.step;
      const gx = (primRelief(p, X + e, Y) - primRelief(p, X - e, Y)) / s2;
      const gy = (primRelief(p, X, Y + e) - primRelief(p, X, Y - e)) / s2;
      const l = Math.min(Math.hypot(gx, gy, 1), 6);
      const g = Math.hypot(gx, gy) || 1;
      const nz = 1 / l, inPlane = Math.sqrt(Math.max(0, 1 - nz * nz));
      out.nx = (-gx / g) * inPlane; out.ny = (-gy / g) * inPlane; out.nz = nz;
      const sx = (this.sd[idx + 1] - this.sd[idx - 1]) / s2;
      const sy = (this.sd[idx - N] - this.sd[idx + N]) / s2;
      const sl = Math.hypot(sx, sy) || 1;
      out.ox = sx / sl; out.oy = sy / sl;
      return out;
    }
    // A jump bigger than J is the edge of a form stacked in front (ear, spire,
    // mushroom); treat it as a cliff, not a slope, so edges do not alias.
    const J = 1.5;
    const side = (v) => (Math.abs(v - hc) > J ? hc : v);
    const hx = (side(h[idx + 1]) - side(h[idx - 1])) / s2;
    const hy = (side(h[idx - N]) - side(h[idx + N])) / s2;
    let l = Math.hypot(hx, hy, 1);
    out.nx = -hx / l; out.ny = -hy / l; out.nz = 1 / l;
    const sx = (this.sd[idx + 1] - this.sd[idx - 1]) / s2;
    const sy = (this.sd[idx - N] - this.sd[idx + N]) / s2;
    l = Math.hypot(sx, sy) || 1;
    out.ox = sx / l; out.oy = sy / l;
    return out;
  }
}

// Lit surface colour for one grid sample (before fog).
function surfaceColor(F, idx, X, Y, seed, nrm) {
  F.normals(idx, nrm);
  const mat = F.mat[idx];
  const lam = nrm.nx * LIGHT[0] + nrm.ny * LIGHT[1] + nrm.nz * LIGHT[2];
  const cav = F.cav[idx];
  let t = 0.14 + lam * 0.98;
  t -= clamp(cav * 0.13, 0, 0.5);
  t += clamp(-cav * 0.05, 0, 0.08);
  t += (fbm(X * 0.11, Y * 0.11, seed, 3) - 0.5) * 0.26;
  const edge = 1 - nrm.nz;
  let c;
  if (mat === MAT_SPIRE) {
    const p = F.prim[idx];
    const ax = p.bx - p.ax, ay = p.by - p.ay, al = Math.hypot(ax, ay);
    const along = ((X - p.ax) * ax + (Y - p.ay) * ay) / al;
    const across = ((X - p.ax) * ay - (Y - p.ay) * ax) / al;
    t += (vnoise(across * 1.6, along * 0.08, seed + 7) - 0.5) * 0.22;
    c = ramp(PAL.spire, t + 0.08);
  } else if (mat === MAT_EAR || mat === MAT_SKIN) {
    c = ramp(PAL.skin, t + 0.05);
    if (mat === MAT_EAR) {
      const p = F.prim[idx];
      const vx = p.bx - p.ax, vy = p.by - p.ay;
      const u = clamp(((X - p.ax) * vx + (Y - p.ay) * vy) / (vx * vx + vy * vy), 0, 1);
      const dx = X - (p.ax + vx * u), dy = Y - (p.ay + vy * u);
      const r = p.ra + (p.rb - p.ra) * u;
      const inner = 1 - Math.hypot(dx, dy) / r;
      c = mixRGB(c, shade(PAL.earInner, (t - 0.55) * 0.5), smoothstep(0.32, 0.75, inner) * 0.75 * smoothstep(0.02, 0.15, u));
    }
  } else {
    c = ramp(PAL.fur, t);
    c = mixRGB(c, PAL.furBounce, clamp(-nrm.ny, 0, 1) * edge * 0.35);
  }
  const rim = edge * clamp(nrm.nx * LIGHT2[0] + nrm.ny * LIGHT2[1], 0, 1) * smoothstep(-2.5, 0, F.sd[idx]);
  c = mixRGB(c, PAL.furRim, rim * 0.55);
  nrm.t = t;
  return c;
}

function finishColor(c, Y, L) {
  if (L.valueShift) c = shade(c, L.valueShift);
  if (L.fog) c = mixRGB(c, fogColor(Y), L.fog);
  return c;
}

function paintAnatomyTile(tg, x0, yTop, k, L, world) {
  const anat = L.anatomy;
  const T = TILE;
  const span = T / k;
  const reach = furReach(L, k);
  const margin = reach + 1.6;
  const prims = anat.cull(x0 - margin, yTop - span - margin, x0 + span + margin, yTop + margin);
  const hasProps = L.props && propsInRect(world, x0 - 6, yTop - span - 6, x0 + span + 6, yTop + 6);
  if (!prims.length && !hasProps) return false;

  const gp = L.gridPx;
  const step = gp / k;
  const n = Math.ceil(T / gp);
  const mg = Math.ceil(margin / step);
  const F = new FieldGrid(anat, prims, x0, yTop, step, n, mg);
  if (!F.any && !hasProps) return false;
  const nrm = {};
  const seed = world.seed + L.seedOffset;

  // 1-2. Painted under-layer at grid resolution, upscaled smoothly.
  const iw = n + 2;
  const img = makeCanvas(iw, iw);
  const ig = img.getContext("2d");
  const data = ig.createImageData(iw, iw);
  for (let j = 0; j < iw; j++) {
    const gj = mg - 1 + j;
    const Y = yTop - (gj - mg + 0.5) * step;
    for (let i = 0; i < iw; i++) {
      const gi = mg - 1 + i;
      const idx = gj * F.N + gi;
      const sd = F.sd[idx];
      const a = clamp(0.5 - (sd + 0.08) / step, 0, 1);
      if (a <= 0 || F.mat[idx] === MAT_SHROOM) continue;
      const X = x0 + (gi - mg + 0.5) * step;
      const c = finishColor(surfaceColor(F, idx, X, Y, seed, nrm), Y, L);
      const o = (j * iw + i) * 4;
      data.data[o] = c[0]; data.data[o + 1] = c[1]; data.data[o + 2] = c[2]; data.data[o + 3] = a * 255;
    }
  }
  ig.putImageData(data, 0, 0);
  tg.imageSmoothingEnabled = true;
  tg.imageSmoothingQuality = "low"; // bilinear: higher filters ring at alpha edges
  tg.drawImage(img, -gp, -gp, iw * gp, iw * gp);

  const toPx = (X, Y) => [(X - x0) * k, (yTop - Y) * k];

  // 3a. Fur: soft clumps with dripping tips, then a fringe at the silhouette.
  paintFur(tg, F, L, x0, yTop, k, span, seed);
  paintDrips(tg, F, L, prims, x0, yTop, k, span, seed);

  // 3b. Spire streaks: long strokes along each monolith's axis.
  const sc = Math.max(0.5, 5 / k);
  for (let cy = Math.floor((yTop - span) / sc); cy <= Math.ceil(yTop / sc); cy++) {
    for (let cx = Math.floor(x0 / sc); cx <= Math.ceil((x0 + span) / sc); cx++) {
      const r = rngFrom(hash2(cx, cy, seed + 11));
      const X = (cx + r()) * sc, Y = (cy + r()) * sc;
      const idx = F.index(X, Y);
      if (idx < 0 || F.mat[idx] !== MAT_SPIRE || F.sd[idx] > -0.2 || r() < 0.55) continue;
      const p = F.prim[idx];
      const ax = p.bx - p.ax, ay = p.by - p.ay, al = Math.hypot(ax, ay);
      const col = finishColor(shade(surfaceColor(F, idx, X, Y, seed, nrm), (r() - 0.45) * 0.25), Y, L);
      const [px, py] = toPx(X, Y);
      streak(tg, px, py, ax / al, -ay / al, (1.5 + r() * 3) * k, Math.max(0.8, 0.12 * k), col, 0.45);
    }
  }

  // 3c. Moss on upward faces and in creases (patchy, denser on the back).
  if (L.moss) {
    const mc = Math.max(0.3, 6 / k);
    for (let cy = Math.floor((yTop - span - 1) / mc); cy <= Math.ceil((yTop + 1) / mc); cy++) {
      for (let cx = Math.floor((x0 - 1) / mc); cx <= Math.ceil((x0 + span + 1) / mc); cx++) {
        const r = rngFrom(hash2(cx, cy, seed + 23));
        const X = (cx + r()) * mc, Y = (cy + r()) * mc;
        const idx = F.index(X, Y);
        if (idx < 0 || F.mat[idx] !== MAT_FUR) continue;
        const sd = F.sd[idx];
        F.normals(idx, nrm);
        const mask = fbm(X * 0.09, Y * 0.09, seed + 29, 3);
        const top = sd > -0.9 && sd < 0.05 && nrm.oy > 0.45 && mask > 0.6;
        const crease = F.cav[idx] > 0.55 && mask > 0.56 && sd < -0.6;
        if (!top && !crease) continue;
        const [px, py] = toPx(X, Y);
        const tint = (lit) => finishColor(mixRGB(ramp(PAL.moss, lit), PAL.fur[1], 0.22), Y, L);
        const count = top ? 9 + Math.floor(r() * 8) : 4;
        for (let d = 0; d < count; d++) {
          const ox = (r() - 0.5) * 0.45, h = (0.07 + r() * 0.14) * (top ? 1 : 0.6);
          const lit = clamp(0.3 + ox * 0.5 * SUN_SIDE + h * 1.5 + (r() - 0.5) * 0.3 + (crease ? -0.15 : 0), 0, 1);
          streak(tg, px + ox * k, py + 0.05 * k, (r() - 0.5) * 0.5, -1, h * k, Math.max(1, 0.035 * k), tint(lit), 0.85);
        }
      }
    }
  }

  // 3d. Props rooted on this layer (mushrooms, trees, the closed eye).
  if (hasProps) drawProps(tg, world, x0, yTop, k, L, seed);
  return true;
}

// Tile cache for one depth layer. Layer pixel space: lx = X * k, ly = -Y * k.
class PaintedLayer {
  constructor(L, world) {
    this.L = L;
    this.world = world;
    this.tiles = new Map();
    this.maxTiles = L.maxTiles || 24;
  }

  tile(tx, ty, k) {
    const key = `${k.toFixed(4)}|${tx}|${ty}`;
    if (this.tiles.has(key)) {
      const t = this.tiles.get(key);
      this.tiles.delete(key);
      this.tiles.set(key, t);
      return t;
    }
    const c = makeCanvas(TILE, TILE);
    const used = this.L.paint(c.getContext("2d"), (tx * TILE) / k, (-ty * TILE) / k, k, this.L, this.world);
    const t = used ? c : null;
    this.tiles.set(key, t);
    while (this.tiles.size > this.maxTiles) this.tiles.delete(this.tiles.keys().next().value);
    return t;
  }

  draw(g, view) {
    const k = view.ppm * view.pr * this.L.par;
    const ox = Math.round(view.W / 2 - view.camX * k);
    const oy = Math.round(view.horizon + view.camY * k);
    const tx0 = Math.floor(-ox / TILE), tx1 = Math.floor((view.W - ox) / TILE);
    const ty0 = Math.floor(-oy / TILE), ty1 = Math.floor((view.H - oy) / TILE);
    for (let ty = ty0; ty <= ty1; ty++) {
      for (let tx = tx0; tx <= tx1; tx++) {
        const t = this.tile(tx, ty, k);
        if (t) g.drawImage(t, tx * TILE + ox, ty * TILE + oy);
      }
    }
  }
}

// ==== src/45-props.js ====
// ---- Props rooted in the anatomy: mushrooms, small trees, the closed eye ----
// Each prop is painted with the same light and fog as the body under it.
// Mushroom caps and stems also exist in the anatomy field (MAT_SHROOM), so
// what you see is what you can stand on.

function propsInRect(world, x0, y0, x1, y1) {
  const P = world.props;
  for (const m of P.mushrooms) if (m.top.x + m.capR > x0 && m.top.x - m.capR < x1 && m.top.y + m.capR > y0 && m.root.y < y1) return true;
  for (const t of P.trees) if (t.x + t.h > x0 && t.x - t.h < x1 && t.y + t.h > y0 && t.y - 0.5 < y1) return true;
  for (const e of P.eyes) if (e.x + e.w > x0 && e.x - e.w < x1 && e.y + e.w > y0 && e.y - e.w < y1) return true;
  return false;
}

function drawProps(g, world, x0, yTop, k, L, seed) {
  const P = (X, Y) => [(X - x0) * k, (yTop - Y) * k];
  const span = TILE / k;
  const inRect = (ax, ay, bx, by) => bx > x0 - 1 && ax < x0 + span + 1 && by > yTop - span - 1 && ay < yTop + 1;
  for (const t of world.props.trees) {
    if (inRect(t.x - t.h, t.y - 0.5, t.x + t.h, t.y + t.h)) drawTree(g, P, k, t, L);
  }
  for (const m of world.props.mushrooms) {
    if (inRect(m.top.x - m.capR - 1, m.root.y - 1, m.top.x + m.capR + 1, m.top.y + m.capR)) drawMushroom(g, P, k, m, L, seed);
  }
  for (const e of world.props.eyes) {
    if (inRect(e.x - e.w, e.y - e.w, e.x + e.w, e.y + e.w)) drawClosedEye(g, P, k, e, L, seed);
  }
}

function drawTree(g, P, k, t, L) {
  const r = rngFrom(t.seed);
  const [bx, by] = P(t.x, t.y);
  const hp = t.h * k;
  const fin = (c, y) => finishColor(c, y, L);
  // Grounding shadow where the plant meets the fur.
  dab(g, bx, by + 0.05 * k, 0.5 * hp * (t.kind === "shrub" ? 0.9 : 0.45), 0.08 * hp + 1, 0, fin(PAL.fur[1], t.y), 0.45);
  // Many small leaf dabs: dark core, sun-side highlights, muted toward the fur.
  const leaf = (lit, y) => fin(mixRGB(ramp(PAL.moss, lit), PAL.fur[1], 0.12), y);
  if (t.kind === "cypress") {
    streak(g, bx, by, 0, -1, hp * 0.2, Math.max(1, 0.05 * k), fin(hex("#4a3b3c"), t.y), 0.9);
    const n = 40 + Math.floor(t.h * 14);
    for (let i = 0; i < n; i++) {
      const yy = 0.1 + Math.pow(r(), 0.8) * 0.9;
      const half = (1 - yy) * 0.2 + 0.035;
      const ox = (r() - 0.5) * 2 * half * hp;
      const side = ox * SUN_SIDE / (half * hp + 1);
      const lit = clamp(0.12 + side * 0.35 + yy * 0.3 + (i > n * 0.75 ? 0.25 : 0) + (r() - 0.5) * 0.2, 0, 1);
      const rr = (0.022 + r() * 0.03) * hp + 0.6;
      dab(g, bx + ox, by - yy * hp, rr * 0.75, rr * 1.4, (r() - 0.5) * 0.4, leaf(lit, t.y + yy * t.h), 0.95);
    }
  } else {
    const n = 34 + Math.floor(t.h * 12);
    for (let i = 0; i < n; i++) {
      const a = r() * Math.PI;
      const rad = Math.sqrt(r());
      const ox = Math.cos(a) * rad * 0.55 * hp, oy = Math.sin(a) * rad * 0.5 * hp;
      const lit = clamp(0.15 + (ox * SUN_SIDE / hp) * 0.5 + (oy / hp) * 0.6 + (i > n * 0.75 ? 0.2 : 0) + (r() - 0.5) * 0.2, 0, 1);
      const rr = (0.035 + r() * 0.04) * hp + 0.6;
      dab(g, bx + ox, by - oy, rr * 1.2, rr, (r() - 0.5) * 0.8, leaf(lit, t.y + oy / k), 0.95);
    }
  }
}

function drawMushroom(g, P, k, m, L, seed) {
  const r = rngFrom(hash2(m.root.x * 100, m.root.y * 100, seed + 41));
  const fin = (c) => finishColor(c, m.top.y, L);
  const [rx, ry] = P(m.root.x, m.root.y);
  const [tx, ty] = P(m.top.x, m.top.y);
  const cr = m.capR * k;
  const sw0 = (0.32 + m.capR * 0.05) * k, sw1 = (0.24 + m.capR * 0.04) * k;
  // Stem: lit on the sun side, lavender on the far side.
  const stem = (w0, w1, col, a, shift) => {
    g.beginPath();
    g.moveTo(rx - w0 + shift, ry);
    g.quadraticCurveTo((rx + tx) / 2 - w0 * 0.8 + shift, (ry + ty) / 2, tx - w1 + shift, ty);
    g.lineTo(tx + w1 + shift, ty);
    g.quadraticCurveTo((rx + tx) / 2 + w0 * 0.8 + shift, (ry + ty) / 2, rx + w0 + shift, ry);
    g.closePath();
    g.fillStyle = css(col, a);
    g.fill();
  };
  stem(sw0, sw1, fin(PAL.shroomStem[0]), 1, 0);
  stem(sw0 * 0.7, sw1 * 0.7, fin(PAL.shroomStem[1]), 0.95, sw1 * 0.25 * SUN_SIDE);
  stem(sw0 * 0.25, sw1 * 0.25, fin(PAL.shroomStem[2]), 0.8, sw1 * 0.55 * SUN_SIDE);
  // Moss collar where the stem roots into fur.
  for (let i = 0; i < 6; i++) {
    dab(g, rx + (r() - 0.5) * sw0 * 3, ry - r() * sw0 * 0.6, sw0 * (0.3 + r() * 0.3), sw0 * 0.22, 0, fin(mixRGB(ramp(PAL.moss, 0.2 + r() * 0.5), PAL.fur[1], 0.2)), 0.9);
  }
  const cy = ty - m.capR * 0.12 * k;
  // Gills: pale underside band with radial lines.
  dab(g, tx, cy + cr * 0.06, cr * 0.96, cr * 0.2, 0, fin(PAL.shroomGill[1]), 1);
  for (let i = 0; i < 14; i++) {
    const u = (i / 13 - 0.5) * 1.8;
    streak(g, tx + u * cr * 0.12, cy + cr * 0.14, u * 0.98, -0.12, cr * 0.4, Math.max(0.6, cr * 0.02), fin(PAL.shroomGill[0]), 0.4);
  }
  // Cap dome.
  const dome = (sx, sy, col, a) => {
    g.beginPath();
    g.moveTo(tx - cr * sx, cy);
    g.bezierCurveTo(tx - cr * sx * 0.95, cy - cr * 0.5 * sy, tx + cr * sx * 0.95, cy - cr * 0.5 * sy, tx + cr * sx, cy);
    g.quadraticCurveTo(tx, cy + cr * 0.12, tx - cr * sx, cy);
    g.closePath();
    g.fillStyle = css(col, a);
    g.fill();
  };
  dome(1, 1, fin(PAL.shroomCap[1]), 1);
  g.save();
  g.beginPath();
  g.moveTo(tx - cr, cy);
  g.bezierCurveTo(tx - cr * 0.95, cy - cr * 0.5, tx + cr * 0.95, cy - cr * 0.5, tx + cr, cy);
  g.quadraticCurveTo(tx, cy + cr * 0.12, tx - cr, cy);
  g.clip();
  // Light from the upper left: lit crown, shadowed right flank, pale rim band.
  const sun = SUN_SIDE;
  dab(g, tx + cr * 0.3 * sun, cy - cr * 0.3, cr * 0.75, cr * 0.28, 0.1 * sun, fin(PAL.shroomCap[2]), 0.85);
  dab(g, tx + cr * 0.42 * sun, cy - cr * 0.34, cr * 0.38, cr * 0.12, 0.15 * sun, fin(PAL.shroomCap[3]), 0.7);
  dab(g, tx - cr * 0.75 * sun, cy - cr * 0.05, cr * 0.5, cr * 0.3, -0.2 * sun, fin(PAL.shroomCap[0]), 0.55);
  dab(g, tx, cy + cr * 0.02, cr * 1.05, cr * 0.07, 0, fin(PAL.shroomGill[2]), 0.6);
  for (let i = 0; i < 9; i++) {
    const a = r() * 2 - 1;
    dab(g, tx + a * cr * 0.8, cy - cr * (0.08 + r() * 0.3) * (1 - a * a), cr * 0.035 + 0.5, cr * 0.025 + 0.5, 0, fin(PAL.shroomCap[3]), 0.7);
  }
  g.restore();
}

// A closed, lashed eye painted into the cranium fur.
function drawClosedEye(g, P, k, e, L, seed) {
  const fin = (c) => finishColor(c, e.y, L);
  const [cx, cy] = P(e.x, e.y);
  const w = e.w * k;
  g.save();
  g.translate(cx, cy);
  g.rotate(-e.tilt);
  g.scale(-(e.outer || -1), 1); // drawn with the outer corner on local -x
  // Socket: a lavender hollow above the lid, warm swell of the lid itself.
  for (let i = 0; i < 6; i++) {
    const s = 1 - i * 0.12;
    dab(g, 0, -w * 0.1, w * 0.66 * s, w * 0.26 * s, 0, fin(PAL.fur[1]), 0.06);
  }
  dab(g, -w * 0.04, -w * 0.07, w * 0.42, w * 0.09, 0, fin(PAL.fur[3]), 0.3);
  dab(g, -w * 0.1, -w * 0.09, w * 0.22, w * 0.035, 0, fin(PAL.fur[4]), 0.35);
  for (let i = 0; i < 4; i++) dab(g, 0, w * 0.1, w * (0.5 - i * 0.08), w * (0.09 - i * 0.015), 0, fin(PAL.fur[1]), 0.07);
  // Lid crease: a tapered crescent sagging downward.
  const lw = w * 0.03;
  g.beginPath();
  g.moveTo(-w * 0.5, -w * 0.02);
  g.quadraticCurveTo(0, w * 0.13, w * 0.48, w * 0.0);
  g.quadraticCurveTo(0, w * 0.13 + lw * 2.2, -w * 0.5, -w * 0.02 + lw * 0.6);
  g.closePath();
  g.fillStyle = css(fin(PAL.lash), 0.95);
  g.fill();
  // Lashes: heavier toward the outer (left) corner.
  const r = rngFrom(seed + 77);
  for (let i = 0; i < 15; i++) {
    const u = i / 14;
    const x = lerp(-w * 0.47, w * 0.4, u);
    const yb = (1 - Math.pow((x / (w * 0.49)), 2)) * w * 0.065 - w * 0.01;
    const len = w * (0.07 + (1 - u) * 0.08 + r() * 0.02);
    const dx = -0.35 - (1 - u) * 0.35, dy = 1;
    const l = Math.hypot(dx, dy);
    g.beginPath();
    g.moveTo(x, yb);
    g.quadraticCurveTo(x + (dx / l) * len * 0.4, yb + (dy / l) * len * 0.7, x + (dx / l) * len - len * 0.15, yb + (dy / l) * len * 0.8);
    g.lineWidth = Math.max(0.8, w * 0.012 * (1.2 - u * 0.5));
    g.lineCap = "round";
    g.strokeStyle = css(fin(PAL.lash), 0.85);
    g.stroke();
  }
  g.restore();
}

// ==== src/50-atmosphere.js ====
// ---- Atmosphere: golden-hour sky, cloud sea, mist bands, paper grain --------
// Distant things dissolve into warm mist; the cloud sea sinks as you climb
// because it is a real plane far below (its screen height follows altitude).

function drawSky(g, view, seed) {
  const { W, H, horizon } = view;
  const grad = g.createLinearGradient(0, horizon - H * 0.78, 0, horizon + H * 0.35);
  grad.addColorStop(0, css(PAL.skyZenith));
  grad.addColorStop(0.3, css(PAL.skyHigh));
  grad.addColorStop(0.55, css(PAL.skyMid));
  grad.addColorStop(0.74, css(PAL.skyLow));
  grad.addColorStop(0.8, css(PAL.horizon));
  grad.addColorStop(1, css(PAL.cloudMid));
  g.fillStyle = grad;
  g.fillRect(0, 0, W, H);

  const sx = W * (0.5 + 0.34 * SUN_SIDE), sy = horizon - H * 0.04;
  const sun = g.createRadialGradient(sx, sy, 0, sx, sy, W * 0.95);
  sun.addColorStop(0, css(PAL.sunCore, 0.95));
  sun.addColorStop(0.18, css(PAL.horizon, 0.55));
  sun.addColorStop(1, css(PAL.horizon, 0));
  g.fillStyle = sun;
  g.fillRect(0, 0, W, H);

  // High wisps: long thin strokes, lit peach underneath, lavender above.
  const r = rngFrom(seed + 501);
  for (let i = 0; i < 9; i++) {
    const y = horizon - H * (0.25 + r() * 0.45);
    const x = r() * W;
    const len = W * (0.2 + r() * 0.35);
    for (let s = 0; s < 5; s++) {
      dab(g, x + (r() - 0.5) * len * 0.3, y + s * 2.5 * view.pr, len * (0.3 + r() * 0.2), (1.2 + r() * 2.2) * view.pr, -0.04,
        s < 2 ? PAL.skyHigh : mixRGB(PAL.cloudLit, PAL.skyMid, 0.4), 0.18);
    }
  }
  // Cumulus banks resting on the horizon.
  for (let c = 0; c < 6; c++) {
    const cx = (c / 5) * W * 1.1 - W * 0.05 + (r() - 0.5) * W * 0.12;
    const size = W * (0.1 + r() * 0.1);
    cloudCluster(g, cx, horizon + H * 0.012, size, rngFrom(seed + 600 + c), 0.3 + r() * 0.2, 0.9);
  }
}

// A billowing cluster of round dabs, lit from the upper left.
function cloudCluster(g, cx, baseY, size, r, fog, alpha) {
  const n = 26;
  const puffs = [];
  for (let i = 0; i < n; i++) {
    const a = Math.PI + r() * Math.PI;
    const rad = Math.pow(r(), 0.7);
    puffs.push({
      x: cx + Math.cos(a) * rad * size * 1.25,
      y: baseY + Math.sin(a) * rad * size * 0.6,
      s: size * (0.18 + r() * 0.24)
    });
  }
  puffs.sort((p, q) => q.y - p.y);
  for (const p of puffs) {
    const h = clamp((baseY - p.y) / (size * 0.7), 0, 1);
    const base = mixRGB(PAL.cloudShade, PAL.cloudMid, h);
    dab(g, p.x, p.y, p.s, p.s * 0.82, 0, mixRGB(base, PAL.horizon, fog), alpha);
    dab(g, p.x + p.s * 0.22 * SUN_SIDE, p.y - p.s * 0.28, p.s * 0.72, p.s * 0.52, 0, mixRGB(mixRGB(PAL.cloudLit, PAL.cloudMid, 0.3 - h * 0.3), PAL.horizon, fog * 0.6), alpha * 0.85);
  }
}

// The cloud sea: a vast plane at y = 0, seen from altitude.
function drawCloudSea(g, view, seed) {
  const par = 0.045;
  const k = view.ppm * view.pr * par;
  const top = view.horizon + view.camY * k;
  if (top > view.H + 50) return;
  const { W, H } = view;
  const fill = g.createLinearGradient(0, top, 0, H);
  fill.addColorStop(0, css(mixRGB(PAL.cloudMid, PAL.horizon, 0.35)));
  fill.addColorStop(1, css(PAL.cloudShade));
  g.fillStyle = fill;
  g.fillRect(0, top, W, H - top + 1);
  // Rows of billows: farther rows smaller and warmer, nearer rows larger and cooler.
  for (let row = 0; row < 4; row++) {
    const depth = 1 + row * 0.6;
    const cellW = 34 / depth;
    const y = top + row * row * 7 * view.pr + row * 9 * view.pr;
    if (y > H + 40) break;
    const xw0 = view.camX - (W / 2) / k - cellW * 2, xw1 = view.camX + (W / 2) / k + cellW * 2;
    for (let c = Math.floor(xw0 / cellW); c <= Math.ceil(xw1 / cellW); c++) {
      const r = rngFrom(hash2(c, row, seed + 900));
      const x = W / 2 + ((c + r()) * cellW - view.camX) * k;
      cloudCluster(g, x, y + r() * 6 * view.pr, cellW * k * (0.5 + r() * 0.4) * (0.8 + row * 0.25), r, 0.35 - row * 0.08, 0.85);
    }
  }
}

// Soft horizontal mist band anchored at world height y in a given depth layer.
function drawMistBand(g, view, y, par, thickness, color, alpha) {
  const k = view.ppm * view.pr * par;
  const sy = view.horizon - (y - view.camY) * k;
  const t = thickness * k;
  if (sy + t < 0 || sy - t > view.H) return;
  const grad = g.createLinearGradient(0, sy - t, 0, sy + t);
  grad.addColorStop(0, css(color, 0));
  grad.addColorStop(0.5, css(color, alpha));
  grad.addColorStop(1, css(color, 0));
  g.fillStyle = grad;
  g.fillRect(0, sy - t, view.W, t * 2);
}

// Low clouds wrapping the body at a given depth: world-anchored clusters.
function drawCloudWrap(g, view, x, y, par, size, seed, fog, alpha) {
  const k = view.ppm * view.pr * par;
  const sx = view.W / 2 + (x - view.camX) * k;
  const sy = view.horizon - (y - view.camY) * k;
  if (sx < -size * k * 2 || sx > view.W + size * k * 2 || sy < -size * k || sy > view.H + size * k) return;
  cloudCluster(g, sx, sy, size * k, rngFrom(seed), fog, alpha);
}

let grainTile = null;
function drawGrain(g, view) {
  if (!grainTile) {
    grainTile = makeCanvas(256, 256);
    const gg = grainTile.getContext("2d");
    const img = gg.createImageData(256, 256);
    const r = rngFrom(4242);
    for (let i = 0; i < 256 * 256; i++) {
      const v = 128 + (r() + r() - 1) * 70;
      img.data[i * 4] = v; img.data[i * 4 + 1] = v; img.data[i * 4 + 2] = v; img.data[i * 4 + 3] = 255;
    }
    gg.putImageData(img, 0, 0);
  }
  g.save();
  g.globalAlpha = 0.07;
  g.globalCompositeOperation = "overlay";
  g.fillStyle = g.createPattern(grainTile, "repeat");
  g.fillRect(0, 0, view.W, view.H);
  g.restore();
  // Gentle lavender vignette pulls focus toward the explorer.
  const v = g.createRadialGradient(view.W / 2, view.H * 0.55, view.H * 0.3, view.W / 2, view.H * 0.55, view.H * 0.8);
  v.addColorStop(0, css(PAL.fur[0], 0));
  v.addColorStop(1, css(PAL.fur[0], 0.22));
  g.fillStyle = v;
  g.fillRect(0, 0, view.W, view.H);
}

// ==== src/55-explorer.js ====
// ---- Explorer: a small traveller, ~4 heads tall, rust tunic, dark hair ------
// Painted with the same upper-left sun as the world: warm rim on the lit
// side, lavender-shifted shadow on the far side, and a contact shadow so the
// feet sit in the fur.

function drawExplorer(g, x, y, hp, facing, pose) {
  const E = PAL.explorer;
  const lean = pose === "climb" ? 0.1 : 0.03;
  g.save();
  g.translate(x, y);
  // Contact shadow (unflipped so it stays under the sun-far side).
  dab(g, -SUN_SIDE * hp * 0.05, -hp * 0.005, hp * 0.24, hp * 0.045, 0, PAL.fur[0], 0.45);
  g.scale(facing, 1);
  g.rotate(lean);
  const lit = SUN_SIDE * facing; // which local x side faces the sun
  const P = (pts, col, a) => {
    g.beginPath();
    g.moveTo(pts[0] * hp, -pts[1] * hp);
    for (let i = 2; i < pts.length; i += 2) g.lineTo(pts[i] * hp, -pts[i + 1] * hp);
    g.closePath();
    g.fillStyle = css(col, a === undefined ? 1 : a);
    g.fill();
  };
  const limb = (x0, y0, x1, y1, x2, y2, w, col) => {
    g.beginPath();
    g.moveTo(x0 * hp, -y0 * hp);
    g.quadraticCurveTo(x1 * hp, -y1 * hp, x2 * hp, -y2 * hp);
    g.lineWidth = w * hp;
    g.lineCap = "round";
    g.lineJoin = "round";
    g.strokeStyle = css(col);
    g.stroke();
  };

  // Back leg and arm (in shadow).
  limb(-0.02, 0.42, -0.07, 0.22, -0.09, 0.06, 0.1, mixRGB(E.trousers, PAL.fur[0], 0.25));
  P([-0.15, 0.0, -0.04, 0.0, -0.04, 0.07, -0.13, 0.07], E.boots);
  limb(-0.06, 0.68, -0.12, 0.58, -0.1, 0.49, 0.075, E.tunicShade);
  dab(g, -0.1 * hp, -0.475 * hp, 0.035 * hp, 0.035 * hp, 0, mixRGB(E.skin, PAL.fur[0], 0.3), 1);

  // Front leg.
  limb(0.03, 0.42, 0.07, 0.24, 0.06, 0.06, 0.105, E.trousers);
  limb(0.0, 0.4, 0.04, 0.24, 0.035, 0.08, 0.035, E.trousersLit);
  P([0.0, 0.0, 0.14, 0.0, 0.14, 0.035, 0.11, 0.075, 0.02, 0.075], E.boots);

  // Tunic: A-line, belted, hem at mid-thigh.
  P([-0.12, 0.72, 0.11, 0.72, 0.14, 0.38, -0.15, 0.38], E.tunic);
  P(lit < 0 ? [-0.12, 0.72, -0.04, 0.72, -0.06, 0.38, -0.15, 0.38] : [0.04, 0.72, 0.11, 0.72, 0.14, 0.38, 0.06, 0.38], E.tunicLit, 0.85);
  P(lit < 0 ? [0.06, 0.72, 0.11, 0.72, 0.14, 0.38, 0.08, 0.38] : [-0.12, 0.72, -0.07, 0.72, -0.09, 0.38, -0.15, 0.38], E.tunicShade, 0.8);
  P([-0.135, 0.5, 0.125, 0.5, 0.127, 0.47, -0.138, 0.47], E.boots, 0.8);
  // Satchel strap and pouch: the traveller's only gear.
  limb(0.09, 0.71, 0.0, 0.6, -0.11, 0.48, 0.02, hex("#5b3f35"));
  P([-0.17, 0.5, -0.09, 0.5, -0.09, 0.41, -0.17, 0.41], hex("#6b4a3c"));

  // Head, face toward facing direction, tousled dark hair over the back.
  dab(g, 0.02 * hp, -0.84 * hp, 0.105 * hp, 0.115 * hp, 0, E.skin, 1);
  dab(g, 0.07 * hp, -0.83 * hp, 0.05 * hp, 0.07 * hp, 0, E.skinLit, 0.7);
  dab(g, -0.02 * hp, -0.75 * hp, 0.045 * hp, 0.03 * hp, 0, E.skin, 1); // neck
  const hair = [
    [-0.04, 0.9, 0.11, 0.1], [0.04, 0.95, 0.09, 0.06], [-0.08, 0.83, 0.07, 0.09],
    [0.08, 0.92, 0.06, 0.045], [-0.1, 0.92, 0.05, 0.06], [0.0, 0.98, 0.06, 0.04]
  ];
  for (const [hx, hy, rx, ry] of hair) dab(g, hx * hp, -hy * hp, rx * hp, ry * hp, 0.2, E.hair, 1);
  dab(g, (lit < 0 ? -0.08 : 0.03) * hp, -0.97 * hp, 0.05 * hp, 0.02 * hp, 0.3, E.hairLit, 0.8);

  // Front arm, relaxed with a slight swing.
  limb(0.05, 0.68, 0.12, 0.57, 0.11, 0.48, 0.078, E.tunic);
  limb(0.04, 0.69, 0.09, 0.6, 0.09, 0.52, 0.03, lit < 0 ? E.tunicShade : E.tunicLit);
  dab(g, 0.11 * hp, -0.465 * hp, 0.036 * hp, 0.036 * hp, 0, E.skin, 1);

  // Sun rim along the lit edge of head and back.
  g.globalAlpha = 0.55;
  dab(g, (lit < 0 ? -0.1 : 0.12) * hp, -0.86 * hp, 0.02 * hp, 0.07 * hp, 0, PAL.furRim, 1);
  dab(g, (lit < 0 ? -0.135 : 0.13) * hp, -0.58 * hp, 0.018 * hp, 0.12 * hp, 0, PAL.furRim, 1);
  g.restore();
}

// ==== src/60-camera.js ====
// ---- Camera: portrait framing that mirrors the reference -------------------
// gameplay:     explorer ~1/14 of the screen height, 60% down, 58% across, so
//               the body mass fills the lower left and sky opens up-right.
// establishing: the title-panel shot - the same world pulled back so the head,
//               ear and closed eye loom over a tiny explorer.
// The horizon (camera height) sits at mid-screen; depth layers converge on it.

const VIEW_PRESETS = {
  gameplay: { spanHeights: 14, ex: 0.58, ey: 0.6 },
  establishing: { spanHeights: 40, focus: "head", fx: 0.6, fy: 0.45 },
  map: { spanHeights: 260, ex: 0.5, ey: 0.6 } // development only: whole-creature layout check
};

function makeView(kind, world, W, H, pr) {
  const preset = VIEW_PRESETS[kind] || VIEW_PRESETS.gameplay;
  const spot = world.explorerSpots[kind] || world.explorerSpots.gameplay;
  const cssH = H / pr;
  const ppm = cssH / (preset.spanHeights * EXPLORER_HEIGHT);
  const k = ppm * pr;
  // Either keep the explorer at a screen anchor, or compose on a named
  // anatomical feature (the establishing shot frames the head).
  const target = preset.focus ? world.focus[preset.focus] : spot;
  const fx = preset.focus ? preset.fx : preset.ex, fy = preset.focus ? preset.fy : preset.ey;
  return {
    kind, W, H, pr, ppm,
    horizon: H * 0.5,
    camX: target.x - (fx - 0.5) * W / k,
    camY: target.y + (fy - 0.5) * H / k,
    explorer: spot
  };
}

function worldToScreen(view, x, y, par) {
  const k = view.ppm * view.pr * (par || 1);
  return [view.W / 2 + (x - view.camX) * k, view.horizon - (y - view.camY) * k];
}

// ==== src/70-scene.js ====
// ---- Scene: composites sky, cloud sea, depth layers, explorer, foreground ---

const LAYER_DEFS = {
  tail: { par: 0.2, fog: 0.72, clumpCell: 1.2, fringeCell: 1.6, minClumpPx: 7, minLockPx: 9, flow: [0.3, -0.95], gridPx: 6, moss: false, props: false, seedOffset: 300, maxTiles: 12 },
  flank: { par: 0.55, fog: 0.4, clumpCell: 0.5, fringeCell: 1.0, minClumpPx: 7, minLockPx: 9, flow: [0.5, -0.87], gridPx: 5, moss: true, props: false, seedOffset: 200, maxTiles: 16 },
  play: { par: 1, fog: 0.05, clumpCell: 0.2, fringeCell: 0.5, minClumpPx: 7, minLockPx: 10, flow: [0.53, -0.85], gridPx: 4, moss: true, props: true, seedOffset: 100, maxTiles: 24 },
  fore: { par: 1.5, fog: 0, valueShift: -0.34, clumpCell: 0.25, fringeCell: 0.5, minClumpPx: 9, minLockPx: 14, flow: [0.3, -0.95], gridPx: 5, moss: false, props: false, seedOffset: 400, maxTiles: 10 }
};

class Scene {
  constructor(world) {
    this.world = world;
    this.layers = {};
    for (const name of Object.keys(LAYER_DEFS)) {
      const L = Object.assign({ name, anatomy: world.layers[name], paint: paintAnatomyTile }, LAYER_DEFS[name]);
      this.layers[name] = new PaintedLayer(L, world);
    }
  }

  render(g, view, opts) {
    const w = this.world, s = w.seed;
    const ey = view.explorer.y;
    drawSky(g, view, s);
    drawCloudSea(g, view, s);
    drawMistBand(g, view, 20, 0.2, 40, PAL.mistWarm, 0.55);
    this.layers.tail.draw(g, view);
    drawCloudWrap(g, view, 96, 8, 0.2, 40, s + 1, 0.3, 0.9);
    drawMistBand(g, view, ey - 4, 0.45, 30, PAL.mistWarm, 0.4);
    this.layers.flank.draw(g, view);
    drawMistBand(g, view, ey - 14, 0.8, 9, PAL.mistWarm, 0.55);
    drawCloudWrap(g, view, view.explorer.x + 14, ey - 16, 0.55, 14, s + 2, 0.25, 0.85);
    this.layers.play.draw(g, view);
    const [sx, sy] = worldToScreen(view, view.explorer.x, view.explorer.y, 1);
    drawExplorer(g, sx, sy, EXPLORER_HEIGHT * view.ppm * view.pr, view.explorer.facing, "idle");
    this.layers.fore.draw(g, view);
    drawGrain(g, view);
    if (opts && opts.collision) drawCollisionOverlay(g, view, w.layers.play);
  }
}

// ---- Collision overlay: the sd = 0 isoline of the play body ----------------
// Green = walkable (faces up), amber = steep wall, red = overhang.
function collisionSegments(anat, x0, y0, x1, y1, step) {
  const nx = Math.ceil((x1 - x0) / step) + 1, ny = Math.ceil((y1 - y0) / step) + 1;
  const prims = anat.cull(x0 - 1, y0 - 1, x1 + 1, y1 + 1);
  const v = new Float32Array(nx * ny), o = {};
  for (let j = 0; j < ny; j++) for (let i = 0; i < nx; i++) v[j * nx + i] = anat.eval(x0 + i * step, y0 + j * step, prims, o).sd;
  const segs = [];
  const cross = (xa, ya, va, xb, yb, vb) => {
    const t = va / (va - vb);
    return [xa + (xb - xa) * t, ya + (yb - ya) * t];
  };
  for (let j = 0; j < ny - 1; j++) {
    for (let i = 0; i < nx - 1; i++) {
      const X = x0 + i * step, Y = y0 + j * step;
      const a = v[j * nx + i], b = v[j * nx + i + 1], c = v[(j + 1) * nx + i + 1], d = v[(j + 1) * nx + i];
      const pts = [];
      if ((a < 0) !== (b < 0)) pts.push(cross(X, Y, a, X + step, Y, b));
      if ((b < 0) !== (c < 0)) pts.push(cross(X + step, Y, b, X + step, Y + step, c));
      if ((c < 0) !== (d < 0)) pts.push(cross(X + step, Y + step, c, X, Y + step, d));
      if ((d < 0) !== (a < 0)) pts.push(cross(X, Y + step, d, X, Y, a));
      for (let p = 0; p + 1 < pts.length; p += 2) {
        const [ax, ay] = pts[p], [bx, by] = pts[p + 1];
        const mx = (ax + bx) / 2, my = (ay + by) / 2, e = step * 0.25;
        const gx = anat.eval(mx + e, my, prims, o).sd - anat.eval(mx - e, my, prims, o).sd;
        const gy = anat.eval(mx, my + e, prims, o).sd - anat.eval(mx, my - e, prims, o).sd;
        const l = Math.hypot(gx, gy) || 1;
        segs.push({ ax, ay, bx, by, ny: gy / l });
      }
    }
  }
  return segs;
}

function drawCollisionOverlay(g, view, anat) {
  const k = view.ppm * view.pr;
  const x0 = view.camX - view.W / 2 / k, x1 = view.camX + view.W / 2 / k;
  const y1 = view.camY + view.horizon / k, y0 = view.camY - (view.H - view.horizon) / k;
  const segs = collisionSegments(anat, x0, y0, x1, y1, Math.max(0.15, 3 / view.ppm));
  g.save();
  g.lineWidth = 2.2 * view.pr;
  g.lineCap = "round";
  for (const s of segs) {
    g.strokeStyle = s.ny > 0.64 ? "rgba(70,230,120,0.95)" : s.ny > -0.3 ? "rgba(255,190,60,0.95)" : "rgba(255,70,90,0.95)";
    const [ax, ay] = worldToScreen(view, s.ax, s.ay, 1);
    const [bx, by] = worldToScreen(view, s.bx, s.by, 1);
    g.beginPath();
    g.moveTo(ax, ay);
    g.lineTo(bx, by);
    g.stroke();
  }
  const [ex, ey] = worldToScreen(view, view.explorer.x, view.explorer.y, 1);
  g.strokeStyle = "rgba(255,255,255,0.95)";
  g.beginPath();
  g.moveTo(ex - 8 * view.pr, ey); g.lineTo(ex + 8 * view.pr, ey);
  g.moveTo(ex, ey - 8 * view.pr); g.lineTo(ex, ey + 8 * view.pr);
  g.stroke();
  g.restore();
}

// ==== src/90-main.js ====
// ---- Bit entry -------------------------------------------------------------
// Stage 1 (visual foundation): one representative scene, interface hidden.
// Draft tuning knobs switch the camera shot and the collision overlay.

const WORLD_SEED = 7331;

window.plethoraBit = {
  meta: {
    title: "Don't Wake It",
    runtime: "plethora-bit@2",
    tags: ["adventure", "climbing", "atmospheric"],
    permissions: []
  },

  async init(ctx) {
    const canvas = ctx.createCanvas2D({ maxDpr: 2, alpha: false, layer: "content", touchAction: "none" });
    const g = canvas.getContext("2d");
    const tune = ctx.tune;
    const tuneChoice = (id, d) => (tune && tune.has(id) ? tune.choice(id) : d) || d;
    const tuneBool = (id, d) => (tune && tune.has(id) ? !!tune.boolean(id) : d);

    let stage = "world";
    let world, scene;
    let disposed = false;
    ctx.onDestroy(() => { disposed = true; });

    const render = () => {
      if (disposed || !scene) return;
      const W = canvas.width, H = canvas.height;
      if (!W || !H) return;
      const pr = W / Math.max(1, ctx.width);
      const view = makeView(tuneChoice("view", "gameplay"), world, W, H, pr);
      scene.render(g, view, { collision: tuneBool("collision_overlay", false) });
    };

    try {
      world = buildWorld(WORLD_SEED);
      scene = new Scene(world);
      stage = "first-frame";
      render();
    } catch (err) {
      ctx.platform.error({ stage, message: String((err && err.message) || err) });
      throw err;
    }

    ctx.onResize(render, { debounceMs: 120 });
    if (tune) tune.onChange(["view", "collision_overlay"], render);
    ctx.markVisualReady("stage1-scene");
    ctx.platform.ready();
  }
};

})();
